version: '3'
services:
  nginx:
    image: "nginx:alpine"
    volumes:
     - ./backend/static:/static
     - ./nginx/nginx.conf:/etc/nginx/sites-enabled/nginx.conf
    depends_on:
     - backend

  backend:
    build: ./backend
    ports:
     - "6001:8080"
     - "6002:8000"
    volumes:
     - ./backend:/backend
    environment:
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - DEBUG=${DEBUG}
     - SECRET_KEY=${SECRET_KEY}
    depends_on:
     - redis
     - postgres

  redis:
    image: "redis:alpine"

  postgres:
    image: "postgres:9.6"
    ports:
     - "6003:5432"
    environment:
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
